branch-defaults:
  main:
    environment: node-express-env
    group_suffix: null
environment-defaults:
  node-express-env:
    branch: main
    repository: origin
global:
  application_name: CMPE295Project
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
